networks:
  bridge:
    driver: bridge    

services:

  nginx:
    container_name: nginx_configserver
    build: nginx/.
    networks:
      - bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./share:/var/share
    environment:
      - TZ=Europe/Moscow